language: python
python:
  - "3.5"

install: "make create_environment; source activate crypto-predict; make requirements"

before_script: cd src

script: pytest

branches:
  only:
  - master
  - develop
