language: python
python:
  - "3.5"

install: "touch .env; make create_environment; source activate crypto-predict; make models"

before_script: cd crypr

script: "pytest --rootdir='./crypr'"

branches:
  only:
  - master
  - develop
