language: python
python:
  - "3.5"

services:
  - docker

install:
  - mv .env_template .env
  - make create_environment
  - source activate crypto-predict
  - make models
  - docker build -f ./docker/Dockerfile -t crypr-api .
  - docker run -p 5000:5000 crypr-api

script:
  - docker ps | grep -q crypr-api
  - pytest ./crypr/tests/unit_test_*.py

branches:
  only:
  - master
  - develop
