language: python
python:
  - "3.5"

services:
  - docker

git:
  depth: false

branches:
  only:
  - master
  - develop
  
install:
  - mv .env_template .env
  - make create_environment
  - source activate crypto-predict
  - make models
  - docker build -f ./docker/Dockerfile -t crypr-api .
  - CONTAINER_ID=$(docker run -d -p 5000:5000 crypr-api)
  - sh ./docker/wait_for_healthy.sh $CONTAINER_ID

script:
  - docker ps | grep -q crypr-api
  - pytest ./crypr/tests/unit_test_*.py

after_success:
  - coveralls
